#!/usr/bin/env bash

A=$(tput setaf 2)
B=$(tput setaf 7)
ERR=$(tput setaf 1)
UUID=$(uuidgen)
DATE=$(date +"%d%m%y-%T")

KY="storePassword=makuro123
keyPassword=makuro123
keyAlias=malikkurosaki
storeFile=/Users/probus/Documents/malikkurosaki.jks
"

CARI='
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
'
REP='apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
'

RELEASE() {
    FL="./android/key.properties"
    [[ ! -f $FL ]] && echo -e "$KY" >$FL
    sed -i.bak "s/$CARI/$REP" z.txt
}

MN() {
    M="
    ------------------------------------------------
    Probus Mobile Report                        Menu
    ------------------------------------------------
    run     menjalankan flutter di emulator
    emu     melihat emolator yang bisa dijaankan
    emur    membuka emulator
    push    push ke github repository
    rels    membuat release
    
    ------------------------------------------------
    Malikkurosaki@2022               version 1.0.0.1
    $UUID
    "
    echo $A"$M"$B
}

RELEASE() {
    confDev='{
  "url": "http://188.166.218.138:3000/apiv2",
  "urlDev": "http://10.0.2.2:3000/apiv2",
  "dev": true,
  "isDebug": false
}'

    confPro='{
  "url": "http://188.166.218.138:3000/apiv2",
  "urlDev": "http://10.0.2.2:3000/apiv2",
  "dev": false,
  "isDebug": false
}'

    fl='v2_config.json'

    echo -n $confPro >$fl
    flutter build apk --release --split-per-abi
    echo -n $confDev >$fl
    open '/Users/probus/documents/projects/flutter/mobile_report/build/app/outputs/apk/release'

}

MN
echo -n "Ketikkan Pilihannya ?: "
read P
case $P in
run) flutter run ;;
emu) flutter devices ;;
emur) flutter emulators --launch Pixel_3_API_27 ;;
push) git add . && git commit -m $DATE && git push origin main ;;
rels) RELEASE ;;
*) echo $ERR"pilih menu yang ada saja"$B ;;
esac
