#!/usr/bin/env bash

help() {
    echo "$(tput setaf 6)
    Usage:
        $0 [options]
    Options:
        -h,     help
        -r,     run
        -db,    database
        -rs,    rest
        -sc,    set config  
        -g, git  
    $(tput sgr0)"
}

cmd() {
    case "$1" in
    pull)
        echo "pull"
        cd server
        git pull
        npm install
        prisma generate
        cd ..
        ;;
    run)
        echo "run server"
        cd server
        pm2 start server.js --name mobile_report -i 1
        ;;
    restart)
        echo "restart server"
        pm2 restart mobile_report
        ;;
    logs)
        pm2 logs
        ;;
    install)
        echo "npm install"
        cd server
        npm install
        cd ..
        ;;
    update)
        echo "npm update"
        cd server
        npm update
        cd ..
        ;;
    gen) 
        echo "prisma generate"
        cd server
        prisma generate
        cd ..
    ;;
    *)
        echo "pull, run, restart, logs, install, update"
        ;;
    esac
}

if [[ $# -eq 0 ]]; then
    help
else
    cmd $1 $2
fi
